config/sfPropelNotificationPlugin/backends.yml:
  class: sfPropelNotificationPluginBackendsConfigurationHandler
  
config/sfPropelNotificationPlugin/types.yml:
  class: sfPropelNotificationPluginTypesConfigurationHandler